type Query {
  categories: [Category]
}

type Category {
  id: ID
  name: String
}

type Mutation {
  createCategory(name: String): [Category]
  updateCategory(id: ID, name: String): [Category]
  deleteCategory(id: ID): [Category]
}

type Subscription {
  categories: [Category]
}
